name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jimpaine/wsl-image-builder:0.1.${{ github.RUN_NUMBER }}

    - name: GH login
      run: gh auth login --with-token <<< "${{github.TOKEN}}"
    - name: Create Release
      run: |
          gh release create v0.1.${{github.RUN_NUMBER}} \
          --title "v0.1.${{github.RUN_NUMBER}}" \
          --notes "# Changes" \
          --repo "${{github.SERVER_URL}}/${{github.REPOSITORY}}"
