name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: echo ${{ github.TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - name: docker build
      run: docker build . --file Dockerfile --tag ghcr.io/jimpaine/wsl-image-builder:0.1.${{ github.RUN_NUMBER }}

    - name: docker push
      if: ${{ github.event_name != 'pull_request' }}
      run: docker push ghcr.io/jimpaine/wsl-image-builder:0.1.${{ github.RUN_NUMBER }}
    - name: GH login
      if: ${{ github.event_name != 'pull_request' }}
      run: gh auth login --with-token <<< "${{github.TOKEN}}"
    - name: Create Release
      if: ${{ github.event_name != 'pull_request' }}
      run: |
          gh release create v0.1.${{github.RUN_NUMBER}} \
          --title "v0.1.${{github.RUN_NUMBER}}" \
          --notes "# Install via PowerShell \n\n ```powershell\ndocker run --name jp-0.1.${{github.RUN_NUMBER}} ghcr.io/jimpaine/wsl-image-builder:0.1.${{github.RUN_NUMBER}} && \ \n docker export --output jp-0.1.${{github.RUN_NUMBER}}.tar jp-0.1.${{github.RUN_NUMBER}} && \ \n wsl --import jp-0.1.${{github.RUN_NUMBER}} c:\jp-0.1.${{github.RUN_NUMBER}} jp-0.1.${{github.RUN_NUMBER}}.tar \n ```" \
          --repo "${{github.SERVER_URL}}/${{github.REPOSITORY}}"
